version: "3"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
      - redis
    # environment:
    # DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable"

  db:
    image: "postgres:latest"
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: yohanes
      POSTGRES_PASSWORD: root
      POSTGRES_DB: market

  redis:
    image: redis:latest
    ports:
      - 6379:6379
